constants:
  file:
    directory: D:\student\heeJin\back\upLoad

spring:
  application:
    name: gallery
  servlet:
    multipart:
      max-file-size: 15MB
  datasource:
    url: jdbc:mariadb://localhost/gallery
    username: root
    password : green502


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml